### ISSUE TITLE
[Epic] Create one container for each Scraping Task

### ISSUE THREAD

**Issue by ebrucucen** [ClimateMisinformation/Scrapers#24]
We want to have a container for each scraping task so that we can schedule and run them independently with an external workflow system.

- [x] BBC
- [x] Dailymail
- [x] Breitbart 
- [x]  Climate discussion nexus
- [x] Cornwall alliance
- [x] Institute for creation research  (put to backlog  because  HTML structure of articles is inconsistent  and there are only 54 of them 
- [x] technocracy news ( another site with inconsistent HTML  structure and invalid string encoding. Parse 38  articles into JSON, not CSV as it escapes the mess in the source articles better )
- [ ] https://thebfd.co.nz/ 
- [ ] https://www.cato.org/
- [ ] https://wattsupwiththat.com/
- [ ] https://friendsofscience.org/
- [ ] https://co2coalition.org
- [ ] https://carbon-sense.com/ 
- [ ] https://friendsofscience.org/
- [ ] http://notrickszone.com/

...
